fbeck_home_home:
    pattern:  /
    defaults: { _controller: fbeckHomeBundle:Home:index }

fbeck_home_bye:
    pattern:  /goodbye-world
    defaults: { _controller: fbeckHomeBundle:Home:bye }

fbeck_home_contact:
    pattern:  /contact
    defaults: { _controller: fbeckHomeBundle:Home:contact }