parameters:
#    fbeck_home.example.class: fbeck\HomeBundle\Example

services:
#    fbeck_home.example:
#        class: %fbeck_home.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
