parameters:
#    fbeck_admin.example.class: fbeck\AdminBundle\Example

services:
#    fbeck_admin.example:
#        class: %fbeck_admin.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
