fbeck_blog:
    resource: "@fbeckBlogBundle/Resources/config/routing.yml"
    prefix:   /blog

fbeck_home:
    resource: "@fbeckHomeBundle/Resources/config/routing.yml"
    prefix:   /

fbeck_user:
    resource: "@fbeckUserBundle/Resources/config/routing.yml"
    prefix:   /
