fbeck_blog_home:
    pattern:  /{page}
    defaults: { _controller: fbeckBlogBundle:Blog:index, page: 1}
    requirements:
        page: \d*

fbeck_blog_view:
    pattern: /article/{id}
    defaults: { _controller: fbeckBlogBundle:Blog:view }
    requirements:
        page: \d*

fbeck_blog_add:
    pattern: /add
    defaults: { _controller: fbeckBlogBundle:Blog:add }

fbeck_blog_edit:
    pattern: /edit/{id}
    defaults: { _controller: fbeckBlogBundle:Blog:edit }
    requirements:
        page: \d*

fbeck_blog_delete:
    pattern: /delete/{id}
    defaults: { _controller: fbeckBlogBundle:Blog:delete }
    requirements:
        page: \d*
